# Generated by Django 2.1.4 on 2019-06-02 08:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('activityid', models.AutoField(primary_key=True, serialize=False)),
                ('activityname', models.CharField(max_length=40)),
                ('activitytype', models.IntegerField(choices=[(0, '学术类'), (1, '体育类'), (2, '科技类'), (3, '文化类')], default=0)),
                ('activitytime', models.DateTimeField()),
                ('activitycapacity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40), django.core.validators.MinValueValidator(1)])),
                ('openenrolltime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activityid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.Activities')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentid', models.AutoField(primary_key=True, serialize=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('activitytime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.Activities')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
